name = "INTSMP Server Modpack"
author = "Fahman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654981517268bedec0dce407183e9113da93aa478f7e24b6d886396ca6b7ac36"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
