name = "INTSMP Server Modpack"
author = "Fahman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7883d3d780c9aa30d5182014686d2186868ae61fac2b14844277710b581e6ece"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
